import networkx as nx

G = nx.Graph()
G.add_nodes_from([1,9])
G.add_edge(1, 2)
G.add_edge(2, 3)
G.add_edge(4, 5)
G.add_edge(5, 6)
G.add_edge(7, 8)
G.add_edge(8, 9)
G.add_edge(1, 4)
G.add_edge(4, 7)
G.add_edge(2, 5)
G.add_edge(5, 8)
G.add_edge(3, 6)
G.add_edge(6, 9)

pos = nx.planar_layout(G)
nx.draw(G, pos=pos, with_labels=True)

is_planar, embedding = nx.check_planarity(G)

print([(n, nbrdict) for n, nbrdict in G.adjacency()])
print(embedding.has_predecessor(1, 2))
print(embedding.has_predecessor(2, 1))
print(embedding.get_edge_data(1, 2))
print(embedding.get_edge_data(2, 5))
print(embedding.get_edge_data(5, 4))
print(embedding.get_edge_data(4, 1))
print(embedding.get_edge_data(2, 3))
print(embedding.get_edge_data(3, 6))
print(embedding.get_edge_data(6, 5))
print(embedding.get_edge_data(5, 2))
print(embedding.get_edge_data(6, 9))
print(embedding.get_edge_data(9, 8))
print(embedding.get_edge_data(8, 5))
print(embedding.get_edge_data(8, 7))
print(embedding.get_edge_data(7, 4))
print(embedding.get_edge_data(1, 2))
print(embedding.next_face_half_edge(1, 2))

print(G.edges())
